### ISSUE TITLE
Can't use mailrise

### ISSUE THREAD

**Issue by hayvan96** [david-kalmakoff/gotify-smtp-emailer#8]
Hi, I'm trying to use this plugin to chain to mailrise.

I'm getting an authentication error : smtp send error: could not send email: 504 5.5.4 Unrecognized authentication type

My configuration : 
```
smtp:
    host: 192.168.1.38
    port: 8025
    fromemail: gotify@local
    toemails:
        - basic_assistant@mailrise.xyz
    subject: "Gotify"
    insecure: true
environment: production
```
thanks !
